#!/bin/sh
set -e

case "$1" in
    configure)
        # Compile man page index
        if command -v mandb >/dev/null 2>&1; then
            mandb -q || true
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        ;;
esac

exit 0
